version: 2
registries:
  k9punsjbolle:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-punsjbolle
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: "/app"
    schedule:
      interval: daily
    registries:
      - k9punsjbolle
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
